### ISSUE TITLE
Gradle plugin requires a newer IDE

### ISSUE THREAD

**Issue by jmhoraze** [googlesamples/android-MediaRecorder#19]
with Android Studio 2.3.3 (both Windows and Mac) I get:
Gradle sync failed: This Gradle plugin requires a newer IDE able to request IDE model level 3. For Android Studio this means version 3.0+

what's going on here?
this is now the third Sample project and they all are not tested / kept up / maintained?

and why do I want (as some web search suggested) to mess with the code and use some work-around adding some other side-effects??

can't we expect clean, working code?

frustrated,
        jm.

**Comment by dturner** [comment]
This should be fixed. The gradle (and other dependencies) have been updated to the latest versions.
