### ISSUE TITLE
How to off Beep sound

### ISSUE THREAD

**Issue by tec-anDro-DeV** [googlesamples/android-MediaRecorder#22]
In MediaRecorder when i start to capturing a video it's create beep sound.
also it's play beep sound when i stop the recording. 

So How to i off this sound.

**Comment by dturner** [comment]
This sounds like an OEM specific issue. Please supply details of manufacturer, model and Android version and reopen this bug.

**Comment by samosudov** [comment]
ZTE Blade S6 Lite with Android version 5.0.2
